printWidth: 80
tabWidth: 2
useTabs: true
semi: false
singleQuote: true
quoteProps: 'as-needed'
jsxSingleQuote: false
trailingComma: 'all'
bracketSpacing: true
bracketSameLine: false
arrowParens: 'always'
rangeStart: 0
rangeEnd: 99999999
requirePragma: false
insertPragma: false
proseWrap: 'preserve'
htmlWhitespaceSensitivity: 'css'
vueIndentScriptAndStyle: false
endOfLine: 'lf'
embeddedLanguageFormatting: 'auto'
singleAttributePerLine: false
